# file: check_DCHdigi_output.py
# author: Alvaro Tolosa-Delgado, CERN 2024
# to run: python3 check_DCHdigi_output.py
# goal: check distance hit-wire and print out a number:
#  0 : calculation of distance hit-wire was done properly
#  1 : problem with calculation of distance hit-wire
#  2 : problem with calculation of hit-projection position onto the wire

import ROOT
import sys


def main():
    exit_code = 0

    # Open debug output file generated by DCHdigi alg
    f = ROOT.TFile("dch_digi_alg_debug.root")

    # Retrieve the hit-wire distance distribution
    hDpw = f.Get("hDpw")
    hDpw.Rebin(10)

    # Retrieve the distance at which the distance distribution has its maximum
    distance_hit_wire_more_frequent = hDpw.GetXaxis().GetBinCenter(hDpw.GetMaximumBin())

    # Check if the distance hit wire has the maximum around d=0.66cm
    if 0.05 < abs(distance_hit_wire_more_frequent - 0.65):
        exit_code += 1

    # Retrieve the hit-projection onto the wire to the wire distance distribution
    hDww = f.Get("hDww")

    # Check the integral, excluding the first bin
    hDww_integral = hDww.Integral(2, -1)
    if hDww_integral != 0:
        exit_code += 2

    return exit_code


if __name__ == "__main__":
    code = main()
    sys.exit(code)
